petclinic:
  database: hsqldb
spring:
  datasource:
    schema: classpath*:db/${petclinic.database}/schema.sql
    data: classpath*:db/${petclinic.database}/data.sql
  profiles:
    active: production

spring.jpa.hibernate.ddl-auto: none

logging.level.org.springframework: INFO
